format: yamanifest
version: 1.0
---
work/MOM6:
  fullpath: /scratch/x77/cy8964/mom6/mom6-ninja-nci/ocean_only_symmetric/MOM6
  hashes:
    binhash: 0cd586802eab5d8f1e63efd767f26719
    md5: cf91168b030c1ce78d74d583bcd840bf
